// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbgcztjylhyjmzvinacg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNiZ2N6dGp5bGh5am16dmluYWNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTgyNTYsImV4cCI6MjA2NTU3NDI1Nn0.rG32pQ3C3pw9NCxTw3xNY3z2mCvNQz3XdvrssppOWUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);